### ISSUE TITLE
Lookup at pubchem outputs incorrect inchi

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms_extras#13]
I noticed that an Inchi loaded from pubchem was stored as:

 'inchi': '"InChI=1S/C12H22O11/c13-1-4-6(16)8(18)9(19)11(21-4)23-12(3-15)10(20)7(17)5(2-14)22-12/h4-11,13-20H,1-3H2/t4-,5-,6-,7-,8+,9-,10+,11-,12+/m1/s1"'

The problem is that there are extra "".  This might cause problems when reading in inchi later by matchms

**Comment by niekdejonge** [comment]
In the code the following section causes the issue:
for result in results_pubchem:
        inchi_pubchem = '"' + result.inchi + '"'
        inchikey_pubchem = result.inchikey
        smiles_pubchem = result.isomeric_smiles

This seems to be done on purpose, but I am not sure why.
Do you know why this is the case @florian-huber? Or can we just remove the extra ""

**Comment by florian-huber** [comment]
Not 100% sure. But I *think* this has historic reasons, which means that at some points one or the other API expected the inchi to start with `"InChI=`.
For instance, I vaguely remember having data where the inchis were stored like `InChI="InChI=...`.

Do you run into any problems with matchms there? Because I would expect that matchms would handle those characters (if not we could quickly change that).

**Comment by niekdejonge** [comment]
No this did not cause any issues, but I encountered it when writing tests and it surprised me and I could imagine it breaking something in matchms. 

Since, it does not break anything I think it is ok to leave it like this and only reopen this issue, if this later gives any issues in matchms
